---
# tasks file for ansible-changeonly

- name: Install awk
  apt:
    name: mawk
    state: present

- name: Copy ansible-changeonly
  copy:
    src: ansible-changeonly
    dest: /usr/local/bin/ansible-changeonly
    owner: root
    group: root
    mode: 0755
